/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    Show: () => import('#features/account/show.controller'),
  },
  administrator: {
    classes: {
      Archive: () => import('#features/administrator/classes/archive.controller'),
      Create: () => import('#features/administrator/classes/create.controller'),
      Delete: () => import('#features/administrator/classes/delete.controller'),
      Paginate: () => import('#features/administrator/classes/paginate.controller'),
      Show: () => import('#features/administrator/classes/show.controller'),
      Unarchive: () => import('#features/administrator/classes/unarchive.controller'),
      Update: () => import('#features/administrator/classes/update.controller'),
    },
    courses: {
      Archive: () => import('#features/administrator/courses/archive.controller'),
      Create: () => import('#features/administrator/courses/create.controller'),
      Delete: () => import('#features/administrator/courses/delete.controller'),
      Paginate: () => import('#features/administrator/courses/paginate.controller'),
      Show: () => import('#features/administrator/courses/show.controller'),
      Unarchive: () => import('#features/administrator/courses/unarchive.controller'),
      Update: () => import('#features/administrator/courses/update.controller'),
    },
    enrollments: {
      Archive: () => import('#features/administrator/enrollments/archive.controller'),
      Delete: () => import('#features/administrator/enrollments/delete.controller'),
      Export: () => import('#features/administrator/enrollments/export.controller'),
      Paginate: () => import('#features/administrator/enrollments/paginate.controller'),
      Show: () => import('#features/administrator/enrollments/show.controller'),
      Unarchive: () => import('#features/administrator/enrollments/unarchive.controller'),
      Update: () => import('#features/administrator/enrollments/update.controller'),
    },
  },
  authentication: {
    SignIn: () => import('#features/authentication/sign-in.controller'),
    SignOut: () => import('#features/authentication/sign-out.controller'),
  },
  storages: {
    Complete: () => import('#features/storages/complete.controller'),
    Create: () => import('#features/storages/create.controller'),
    Delete: () => import('#features/storages/delete.controller'),
    Download: () => import('#features/storages/download.controller'),
    Parts: () => import('#features/storages/parts.controller'),
  },
}
