/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as AuthenticationLayoutRouteImport } from './routes/authentication/layout'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPrivacidadeRouteImport } from './routes/_public/privacidade'
import { Route as PublicSobreRouteImport } from './routes/_public/sobre'
import { Route as PublicTermosRouteImport } from './routes/_public/termos'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as PublicCursosSlugRouteImport } from './routes/_public/cursos/$slug'
import { Route as PublicMatriculaIndexRouteImport } from './routes/_public/matricula/index'
import { Route as PublicMatriculaProtocolRouteImport } from './routes/_public/matricula/$protocol'
import { Route as PrivateAdminCursosIndexRouteImport } from './routes/_private/admin/cursos/index'
import { Route as PrivateAdminCursosNovoRouteImport } from './routes/_private/admin/cursos/novo'
import { Route as PrivateAdminMatriculasIndexRouteImport } from './routes/_private/admin/matriculas/index'
import { Route as PrivateAdminTurmasIndexRouteImport } from './routes/_private/admin/turmas/index'
import { Route as PrivateAdminTurmasNovaRouteImport } from './routes/_private/admin/turmas/nova'
import { Route as PrivateAdminCursosIdIndexRouteImport } from './routes/_private/admin/cursos/$id/index'
import { Route as PrivateAdminMatriculasIdIndexRouteImport } from './routes/_private/admin/matriculas/$id/index'
import { Route as PrivateAdminTurmasIdIndexRouteImport } from './routes/_private/admin/turmas/$id/index'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLayoutRoute = AuthenticationLayoutRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))
const PublicPrivacidadeRoute = PublicPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/privacidade.lazy').then((d) => d.Route),
)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/sobre.lazy').then((d) => d.Route))
const PublicTermosRoute = PublicTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/termos.lazy').then((d) => d.Route),
)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationLayoutRoute,
} as any).lazy(() =>
  import('./routes/authentication/index.lazy').then((d) => d.Route),
)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/index.lazy').then((d) => d.Route),
)
const PublicCursosSlugRoute = PublicCursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/cursos/$slug.lazy').then((d) => d.Route),
)
const PublicMatriculaIndexRoute = PublicMatriculaIndexRouteImport.update({
  id: '/matricula/',
  path: '/matricula/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/matricula/index.lazy').then((d) => d.Route),
)
const PublicMatriculaProtocolRoute = PublicMatriculaProtocolRouteImport.update({
  id: '/matricula/$protocol',
  path: '/matricula/$protocol',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/matricula/$protocol.lazy').then((d) => d.Route),
)
const PrivateAdminCursosIndexRoute = PrivateAdminCursosIndexRouteImport.update({
  id: '/admin/cursos/',
  path: '/admin/cursos/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/cursos/index.lazy').then((d) => d.Route),
)
const PrivateAdminCursosNovoRoute = PrivateAdminCursosNovoRouteImport.update({
  id: '/admin/cursos/novo',
  path: '/admin/cursos/novo',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/cursos/novo.lazy').then((d) => d.Route),
)
const PrivateAdminMatriculasIndexRoute =
  PrivateAdminMatriculasIndexRouteImport.update({
    id: '/admin/matriculas/',
    path: '/admin/matriculas/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/matriculas/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminTurmasIndexRoute = PrivateAdminTurmasIndexRouteImport.update({
  id: '/admin/turmas/',
  path: '/admin/turmas/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/turmas/index.lazy').then((d) => d.Route),
)
const PrivateAdminTurmasNovaRoute = PrivateAdminTurmasNovaRouteImport.update({
  id: '/admin/turmas/nova',
  path: '/admin/turmas/nova',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/turmas/nova.lazy').then((d) => d.Route),
)
const PrivateAdminCursosIdIndexRoute =
  PrivateAdminCursosIdIndexRouteImport.update({
    id: '/admin/cursos/$id/',
    path: '/admin/cursos/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/cursos/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminMatriculasIdIndexRoute =
  PrivateAdminMatriculasIdIndexRouteImport.update({
    id: '/admin/matriculas/$id/',
    path: '/admin/matriculas/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/matriculas/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminTurmasIdIndexRoute =
  PrivateAdminTurmasIdIndexRouteImport.update({
    id: '/admin/turmas/$id/',
    path: '/admin/turmas/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/turmas/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/privacidade': typeof PublicPrivacidadeRoute
  '/sobre': typeof PublicSobreRoute
  '/termos': typeof PublicTermosRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/cursos/$slug': typeof PublicCursosSlugRoute
  '/matricula/$protocol': typeof PublicMatriculaProtocolRoute
  '/admin/': typeof PrivateAdminIndexRoute
  '/matricula/': typeof PublicMatriculaIndexRoute
  '/admin/cursos/novo': typeof PrivateAdminCursosNovoRoute
  '/admin/turmas/nova': typeof PrivateAdminTurmasNovaRoute
  '/admin/cursos/': typeof PrivateAdminCursosIndexRoute
  '/admin/matriculas/': typeof PrivateAdminMatriculasIndexRoute
  '/admin/turmas/': typeof PrivateAdminTurmasIndexRoute
  '/admin/cursos/$id/': typeof PrivateAdminCursosIdIndexRoute
  '/admin/matriculas/$id/': typeof PrivateAdminMatriculasIdIndexRoute
  '/admin/turmas/$id/': typeof PrivateAdminTurmasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/sobre': typeof PublicSobreRoute
  '/termos': typeof PublicTermosRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/cursos/$slug': typeof PublicCursosSlugRoute
  '/matricula/$protocol': typeof PublicMatriculaProtocolRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/matricula': typeof PublicMatriculaIndexRoute
  '/admin/cursos/novo': typeof PrivateAdminCursosNovoRoute
  '/admin/turmas/nova': typeof PrivateAdminTurmasNovaRoute
  '/admin/cursos': typeof PrivateAdminCursosIndexRoute
  '/admin/matriculas': typeof PrivateAdminMatriculasIndexRoute
  '/admin/turmas': typeof PrivateAdminTurmasIndexRoute
  '/admin/cursos/$id': typeof PrivateAdminCursosIdIndexRoute
  '/admin/matriculas/$id': typeof PrivateAdminMatriculasIdIndexRoute
  '/admin/turmas/$id': typeof PrivateAdminTurmasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/_public/privacidade': typeof PublicPrivacidadeRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/termos': typeof PublicTermosRoute
  '/_public/': typeof PublicIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/_public/cursos/$slug': typeof PublicCursosSlugRoute
  '/_public/matricula/$protocol': typeof PublicMatriculaProtocolRoute
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_public/matricula/': typeof PublicMatriculaIndexRoute
  '/_private/admin/cursos/novo': typeof PrivateAdminCursosNovoRoute
  '/_private/admin/turmas/nova': typeof PrivateAdminTurmasNovaRoute
  '/_private/admin/cursos/': typeof PrivateAdminCursosIndexRoute
  '/_private/admin/matriculas/': typeof PrivateAdminMatriculasIndexRoute
  '/_private/admin/turmas/': typeof PrivateAdminTurmasIndexRoute
  '/_private/admin/cursos/$id/': typeof PrivateAdminCursosIdIndexRoute
  '/_private/admin/matriculas/$id/': typeof PrivateAdminMatriculasIdIndexRoute
  '/_private/admin/turmas/$id/': typeof PrivateAdminTurmasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/authentication/'
    | '/cursos/$slug'
    | '/matricula/$protocol'
    | '/admin/'
    | '/matricula/'
    | '/admin/cursos/novo'
    | '/admin/turmas/nova'
    | '/admin/cursos/'
    | '/admin/matriculas/'
    | '/admin/turmas/'
    | '/admin/cursos/$id/'
    | '/admin/matriculas/$id/'
    | '/admin/turmas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/authentication'
    | '/cursos/$slug'
    | '/matricula/$protocol'
    | '/admin'
    | '/matricula'
    | '/admin/cursos/novo'
    | '/admin/turmas/nova'
    | '/admin/cursos'
    | '/admin/matriculas'
    | '/admin/turmas'
    | '/admin/cursos/$id'
    | '/admin/matriculas/$id'
    | '/admin/turmas/$id'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/authentication'
    | '/_public/privacidade'
    | '/_public/sobre'
    | '/_public/termos'
    | '/_public/'
    | '/authentication/'
    | '/_public/cursos/$slug'
    | '/_public/matricula/$protocol'
    | '/_private/admin/'
    | '/_public/matricula/'
    | '/_private/admin/cursos/novo'
    | '/_private/admin/turmas/nova'
    | '/_private/admin/cursos/'
    | '/_private/admin/matriculas/'
    | '/_private/admin/turmas/'
    | '/_private/admin/cursos/$id/'
    | '/_private/admin/matriculas/$id/'
    | '/_private/admin/turmas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthenticationLayoutRoute: typeof AuthenticationLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/privacidade': {
      id: '/_public/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PublicPrivacidadeRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/termos': {
      id: '/_public/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof PublicTermosRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/cursos/$slug': {
      id: '/_public/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof PublicCursosSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/matricula/': {
      id: '/_public/matricula/'
      path: '/matricula'
      fullPath: '/matricula/'
      preLoaderRoute: typeof PublicMatriculaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/matricula/$protocol': {
      id: '/_public/matricula/$protocol'
      path: '/matricula/$protocol'
      fullPath: '/matricula/$protocol'
      preLoaderRoute: typeof PublicMatriculaProtocolRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/admin/cursos/': {
      id: '/_private/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof PrivateAdminCursosIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/cursos/novo': {
      id: '/_private/admin/cursos/novo'
      path: '/admin/cursos/novo'
      fullPath: '/admin/cursos/novo'
      preLoaderRoute: typeof PrivateAdminCursosNovoRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/matriculas/': {
      id: '/_private/admin/matriculas/'
      path: '/admin/matriculas'
      fullPath: '/admin/matriculas/'
      preLoaderRoute: typeof PrivateAdminMatriculasIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/turmas/': {
      id: '/_private/admin/turmas/'
      path: '/admin/turmas'
      fullPath: '/admin/turmas/'
      preLoaderRoute: typeof PrivateAdminTurmasIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/turmas/nova': {
      id: '/_private/admin/turmas/nova'
      path: '/admin/turmas/nova'
      fullPath: '/admin/turmas/nova'
      preLoaderRoute: typeof PrivateAdminTurmasNovaRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/cursos/$id/': {
      id: '/_private/admin/cursos/$id/'
      path: '/admin/cursos/$id'
      fullPath: '/admin/cursos/$id/'
      preLoaderRoute: typeof PrivateAdminCursosIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/matriculas/$id/': {
      id: '/_private/admin/matriculas/$id/'
      path: '/admin/matriculas/$id'
      fullPath: '/admin/matriculas/$id/'
      preLoaderRoute: typeof PrivateAdminMatriculasIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/turmas/$id/': {
      id: '/_private/admin/turmas/$id/'
      path: '/admin/turmas/$id'
      fullPath: '/admin/turmas/$id/'
      preLoaderRoute: typeof PrivateAdminTurmasIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
  PrivateAdminCursosNovoRoute: typeof PrivateAdminCursosNovoRoute
  PrivateAdminTurmasNovaRoute: typeof PrivateAdminTurmasNovaRoute
  PrivateAdminCursosIndexRoute: typeof PrivateAdminCursosIndexRoute
  PrivateAdminMatriculasIndexRoute: typeof PrivateAdminMatriculasIndexRoute
  PrivateAdminTurmasIndexRoute: typeof PrivateAdminTurmasIndexRoute
  PrivateAdminCursosIdIndexRoute: typeof PrivateAdminCursosIdIndexRoute
  PrivateAdminMatriculasIdIndexRoute: typeof PrivateAdminMatriculasIdIndexRoute
  PrivateAdminTurmasIdIndexRoute: typeof PrivateAdminTurmasIdIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
  PrivateAdminCursosNovoRoute: PrivateAdminCursosNovoRoute,
  PrivateAdminTurmasNovaRoute: PrivateAdminTurmasNovaRoute,
  PrivateAdminCursosIndexRoute: PrivateAdminCursosIndexRoute,
  PrivateAdminMatriculasIndexRoute: PrivateAdminMatriculasIndexRoute,
  PrivateAdminTurmasIndexRoute: PrivateAdminTurmasIndexRoute,
  PrivateAdminCursosIdIndexRoute: PrivateAdminCursosIdIndexRoute,
  PrivateAdminMatriculasIdIndexRoute: PrivateAdminMatriculasIdIndexRoute,
  PrivateAdminTurmasIdIndexRoute: PrivateAdminTurmasIdIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicPrivacidadeRoute: typeof PublicPrivacidadeRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicTermosRoute: typeof PublicTermosRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCursosSlugRoute: typeof PublicCursosSlugRoute
  PublicMatriculaProtocolRoute: typeof PublicMatriculaProtocolRoute
  PublicMatriculaIndexRoute: typeof PublicMatriculaIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicPrivacidadeRoute: PublicPrivacidadeRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicTermosRoute: PublicTermosRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCursosSlugRoute: PublicCursosSlugRoute,
  PublicMatriculaProtocolRoute: PublicMatriculaProtocolRoute,
  PublicMatriculaIndexRoute: PublicMatriculaIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AuthenticationLayoutRouteChildren {
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationLayoutRouteChildren: AuthenticationLayoutRouteChildren = {
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationLayoutRouteWithChildren =
  AuthenticationLayoutRoute._addFileChildren(AuthenticationLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthenticationLayoutRoute: AuthenticationLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
