/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as AuthenticationLayoutRouteImport } from './routes/authentication/layout'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicPartnersRouteImport } from './routes/_public/partners'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PrivateAdministratorIndexRouteImport } from './routes/_private/administrator/index'
import { Route as PrivatePortalIndexRouteImport } from './routes/_private/portal/index'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile/index'
import { Route as PrivateProfileEditRouteImport } from './routes/_private/profile/edit'
import { Route as PublicCoursesSlugRouteImport } from './routes/_public/courses/$slug'
import { Route as PublicEnrollmentIndexRouteImport } from './routes/_public/enrollment/index'
import { Route as PublicEnrollmentProtocolRouteImport } from './routes/_public/enrollment/$protocol'
import { Route as AuthenticationSignInIndexRouteImport } from './routes/authentication/_sign-in/index'
import { Route as PrivateAdministratorClassesIndexRouteImport } from './routes/_private/administrator/classes/index'
import { Route as PrivateAdministratorClassesNewRouteImport } from './routes/_private/administrator/classes/new'
import { Route as PrivateAdministratorCoursesIndexRouteImport } from './routes/_private/administrator/courses/index'
import { Route as PrivateAdministratorEnrollmentsIndexRouteImport } from './routes/_private/administrator/enrollments/index'
import { Route as PrivateAdministratorPartnersIndexRouteImport } from './routes/_private/administrator/partners/index'
import { Route as PrivateAdministratorUsersIndexRouteImport } from './routes/_private/administrator/users/index'
import { Route as AuthenticationInviteTokenIndexRouteImport } from './routes/authentication/invite/$token/index'
import { Route as PrivateAdministratorClassesIdIndexRouteImport } from './routes/_private/administrator/classes/$id/index'
import { Route as PrivateAdministratorClassesIdEditRouteImport } from './routes/_private/administrator/classes/$id/edit'
import { Route as PrivateAdministratorCoursesIdIndexRouteImport } from './routes/_private/administrator/courses/$id/index'
import { Route as PrivateAdministratorCoursesIdEditRouteImport } from './routes/_private/administrator/courses/$id/edit'
import { Route as PrivateAdministratorEnrollmentsIdIndexRouteImport } from './routes/_private/administrator/enrollments/$id/index'
import { Route as PrivateAdministratorPartnersIdIndexRouteImport } from './routes/_private/administrator/partners/$id/index'
import { Route as PrivateAdministratorPartnersIdEditRouteImport } from './routes/_private/administrator/partners/$id/edit'
import { Route as PrivateAdministratorUsersIdIndexRouteImport } from './routes/_private/administrator/users/$id/index'
import { Route as PrivateAdministratorUsersIdEditRouteImport } from './routes/_private/administrator/users/$id/edit'

const PrivateAdministratorCoursesNewLazyRouteImport = createFileRoute(
  '/_private/administrator/courses/new',
)()
const PrivateAdministratorPartnersNewLazyRouteImport = createFileRoute(
  '/_private/administrator/partners/new',
)()
const PrivateAdministratorUsersNewLazyRouteImport = createFileRoute(
  '/_private/administrator/users/new',
)()

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLayoutRoute = AuthenticationLayoutRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/about.lazy').then((d) => d.Route))
const PublicPartnersRoute = PublicPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/partners.lazy').then((d) => d.Route),
)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/privacy.lazy').then((d) => d.Route),
)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/terms.lazy').then((d) => d.Route))
const PrivateAdministratorIndexRoute =
  PrivateAdministratorIndexRouteImport.update({
    id: '/administrator/',
    path: '/administrator/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/index.lazy').then((d) => d.Route),
  )
const PrivatePortalIndexRoute = PrivatePortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/portal/index.lazy').then((d) => d.Route),
)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/profile/index.lazy').then((d) => d.Route),
)
const PrivateProfileEditRoute = PrivateProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/profile/edit.lazy').then((d) => d.Route),
)
const PublicCoursesSlugRoute = PublicCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/courses/$slug.lazy').then((d) => d.Route),
)
const PublicEnrollmentIndexRoute = PublicEnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/enrollment/index.lazy').then((d) => d.Route),
)
const PublicEnrollmentProtocolRoute =
  PublicEnrollmentProtocolRouteImport.update({
    id: '/enrollment/$protocol',
    path: '/enrollment/$protocol',
    getParentRoute: () => PublicLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_public/enrollment/$protocol.lazy').then((d) => d.Route),
  )
const AuthenticationSignInIndexRoute =
  AuthenticationSignInIndexRouteImport.update({
    id: '/_sign-in/',
    path: '/',
    getParentRoute: () => AuthenticationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/authentication/_sign-in/index.lazy').then((d) => d.Route),
  )
const PrivateAdministratorClassesIndexRoute =
  PrivateAdministratorClassesIndexRouteImport.update({
    id: '/administrator/classes/',
    path: '/administrator/classes/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/classes/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorClassesNewRoute =
  PrivateAdministratorClassesNewRouteImport.update({
    id: '/administrator/classes/new',
    path: '/administrator/classes/new',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/classes/new.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorCoursesIndexRoute =
  PrivateAdministratorCoursesIndexRouteImport.update({
    id: '/administrator/courses/',
    path: '/administrator/courses/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/courses/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorCoursesNewLazyRoute =
  PrivateAdministratorCoursesNewLazyRouteImport.update({
    id: '/administrator/courses/new',
    path: '/administrator/courses/new',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/courses/new.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorEnrollmentsIndexRoute =
  PrivateAdministratorEnrollmentsIndexRouteImport.update({
    id: '/administrator/enrollments/',
    path: '/administrator/enrollments/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/enrollments/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorPartnersIndexRoute =
  PrivateAdministratorPartnersIndexRouteImport.update({
    id: '/administrator/partners/',
    path: '/administrator/partners/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/partners/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorPartnersNewLazyRoute =
  PrivateAdministratorPartnersNewLazyRouteImport.update({
    id: '/administrator/partners/new',
    path: '/administrator/partners/new',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/partners/new.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorUsersIndexRoute =
  PrivateAdministratorUsersIndexRouteImport.update({
    id: '/administrator/users/',
    path: '/administrator/users/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/users/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorUsersNewLazyRoute =
  PrivateAdministratorUsersNewLazyRouteImport.update({
    id: '/administrator/users/new',
    path: '/administrator/users/new',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/users/new.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticationInviteTokenIndexRoute =
  AuthenticationInviteTokenIndexRouteImport.update({
    id: '/invite/$token/',
    path: '/invite/$token/',
    getParentRoute: () => AuthenticationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/authentication/invite/$token/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorClassesIdIndexRoute =
  PrivateAdministratorClassesIdIndexRouteImport.update({
    id: '/administrator/classes/$id/',
    path: '/administrator/classes/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/classes/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorClassesIdEditRoute =
  PrivateAdministratorClassesIdEditRouteImport.update({
    id: '/administrator/classes/$id/edit',
    path: '/administrator/classes/$id/edit',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/classes/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorCoursesIdIndexRoute =
  PrivateAdministratorCoursesIdIndexRouteImport.update({
    id: '/administrator/courses/$id/',
    path: '/administrator/courses/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/courses/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorCoursesIdEditRoute =
  PrivateAdministratorCoursesIdEditRouteImport.update({
    id: '/administrator/courses/$id/edit',
    path: '/administrator/courses/$id/edit',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/courses/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorEnrollmentsIdIndexRoute =
  PrivateAdministratorEnrollmentsIdIndexRouteImport.update({
    id: '/administrator/enrollments/$id/',
    path: '/administrator/enrollments/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/enrollments/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorPartnersIdIndexRoute =
  PrivateAdministratorPartnersIdIndexRouteImport.update({
    id: '/administrator/partners/$id/',
    path: '/administrator/partners/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/partners/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorPartnersIdEditRoute =
  PrivateAdministratorPartnersIdEditRouteImport.update({
    id: '/administrator/partners/$id/edit',
    path: '/administrator/partners/$id/edit',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/partners/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorUsersIdIndexRoute =
  PrivateAdministratorUsersIdIndexRouteImport.update({
    id: '/administrator/users/$id/',
    path: '/administrator/users/$id/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/users/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdministratorUsersIdEditRoute =
  PrivateAdministratorUsersIdEditRouteImport.update({
    id: '/administrator/users/$id/edit',
    path: '/administrator/users/$id/edit',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/administrator/users/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/partners': typeof PublicPartnersRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/courses/$slug': typeof PublicCoursesSlugRoute
  '/enrollment/$protocol': typeof PublicEnrollmentProtocolRoute
  '/administrator/': typeof PrivateAdministratorIndexRoute
  '/portal/': typeof PrivatePortalIndexRoute
  '/profile/': typeof PrivateProfileIndexRoute
  '/enrollment/': typeof PublicEnrollmentIndexRoute
  '/authentication/': typeof AuthenticationSignInIndexRoute
  '/administrator/classes/new': typeof PrivateAdministratorClassesNewRoute
  '/administrator/courses/new': typeof PrivateAdministratorCoursesNewLazyRoute
  '/administrator/partners/new': typeof PrivateAdministratorPartnersNewLazyRoute
  '/administrator/users/new': typeof PrivateAdministratorUsersNewLazyRoute
  '/administrator/classes/': typeof PrivateAdministratorClassesIndexRoute
  '/administrator/courses/': typeof PrivateAdministratorCoursesIndexRoute
  '/administrator/enrollments/': typeof PrivateAdministratorEnrollmentsIndexRoute
  '/administrator/partners/': typeof PrivateAdministratorPartnersIndexRoute
  '/administrator/users/': typeof PrivateAdministratorUsersIndexRoute
  '/authentication/invite/$token/': typeof AuthenticationInviteTokenIndexRoute
  '/administrator/classes/$id/edit': typeof PrivateAdministratorClassesIdEditRoute
  '/administrator/courses/$id/edit': typeof PrivateAdministratorCoursesIdEditRoute
  '/administrator/partners/$id/edit': typeof PrivateAdministratorPartnersIdEditRoute
  '/administrator/users/$id/edit': typeof PrivateAdministratorUsersIdEditRoute
  '/administrator/classes/$id/': typeof PrivateAdministratorClassesIdIndexRoute
  '/administrator/courses/$id/': typeof PrivateAdministratorCoursesIdIndexRoute
  '/administrator/enrollments/$id/': typeof PrivateAdministratorEnrollmentsIdIndexRoute
  '/administrator/partners/$id/': typeof PrivateAdministratorPartnersIdIndexRoute
  '/administrator/users/$id/': typeof PrivateAdministratorUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/partners': typeof PublicPartnersRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/courses/$slug': typeof PublicCoursesSlugRoute
  '/enrollment/$protocol': typeof PublicEnrollmentProtocolRoute
  '/administrator': typeof PrivateAdministratorIndexRoute
  '/portal': typeof PrivatePortalIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/enrollment': typeof PublicEnrollmentIndexRoute
  '/authentication': typeof AuthenticationSignInIndexRoute
  '/administrator/classes/new': typeof PrivateAdministratorClassesNewRoute
  '/administrator/courses/new': typeof PrivateAdministratorCoursesNewLazyRoute
  '/administrator/partners/new': typeof PrivateAdministratorPartnersNewLazyRoute
  '/administrator/users/new': typeof PrivateAdministratorUsersNewLazyRoute
  '/administrator/classes': typeof PrivateAdministratorClassesIndexRoute
  '/administrator/courses': typeof PrivateAdministratorCoursesIndexRoute
  '/administrator/enrollments': typeof PrivateAdministratorEnrollmentsIndexRoute
  '/administrator/partners': typeof PrivateAdministratorPartnersIndexRoute
  '/administrator/users': typeof PrivateAdministratorUsersIndexRoute
  '/authentication/invite/$token': typeof AuthenticationInviteTokenIndexRoute
  '/administrator/classes/$id/edit': typeof PrivateAdministratorClassesIdEditRoute
  '/administrator/courses/$id/edit': typeof PrivateAdministratorCoursesIdEditRoute
  '/administrator/partners/$id/edit': typeof PrivateAdministratorPartnersIdEditRoute
  '/administrator/users/$id/edit': typeof PrivateAdministratorUsersIdEditRoute
  '/administrator/classes/$id': typeof PrivateAdministratorClassesIdIndexRoute
  '/administrator/courses/$id': typeof PrivateAdministratorCoursesIdIndexRoute
  '/administrator/enrollments/$id': typeof PrivateAdministratorEnrollmentsIdIndexRoute
  '/administrator/partners/$id': typeof PrivateAdministratorPartnersIdIndexRoute
  '/administrator/users/$id': typeof PrivateAdministratorUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/partners': typeof PublicPartnersRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/profile/edit': typeof PrivateProfileEditRoute
  '/_public/courses/$slug': typeof PublicCoursesSlugRoute
  '/_public/enrollment/$protocol': typeof PublicEnrollmentProtocolRoute
  '/_private/administrator/': typeof PrivateAdministratorIndexRoute
  '/_private/portal/': typeof PrivatePortalIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_public/enrollment/': typeof PublicEnrollmentIndexRoute
  '/authentication/_sign-in/': typeof AuthenticationSignInIndexRoute
  '/_private/administrator/classes/new': typeof PrivateAdministratorClassesNewRoute
  '/_private/administrator/courses/new': typeof PrivateAdministratorCoursesNewLazyRoute
  '/_private/administrator/partners/new': typeof PrivateAdministratorPartnersNewLazyRoute
  '/_private/administrator/users/new': typeof PrivateAdministratorUsersNewLazyRoute
  '/_private/administrator/classes/': typeof PrivateAdministratorClassesIndexRoute
  '/_private/administrator/courses/': typeof PrivateAdministratorCoursesIndexRoute
  '/_private/administrator/enrollments/': typeof PrivateAdministratorEnrollmentsIndexRoute
  '/_private/administrator/partners/': typeof PrivateAdministratorPartnersIndexRoute
  '/_private/administrator/users/': typeof PrivateAdministratorUsersIndexRoute
  '/authentication/invite/$token/': typeof AuthenticationInviteTokenIndexRoute
  '/_private/administrator/classes/$id/edit': typeof PrivateAdministratorClassesIdEditRoute
  '/_private/administrator/courses/$id/edit': typeof PrivateAdministratorCoursesIdEditRoute
  '/_private/administrator/partners/$id/edit': typeof PrivateAdministratorPartnersIdEditRoute
  '/_private/administrator/users/$id/edit': typeof PrivateAdministratorUsersIdEditRoute
  '/_private/administrator/classes/$id/': typeof PrivateAdministratorClassesIdIndexRoute
  '/_private/administrator/courses/$id/': typeof PrivateAdministratorCoursesIdIndexRoute
  '/_private/administrator/enrollments/$id/': typeof PrivateAdministratorEnrollmentsIdIndexRoute
  '/_private/administrator/partners/$id/': typeof PrivateAdministratorPartnersIdIndexRoute
  '/_private/administrator/users/$id/': typeof PrivateAdministratorUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication'
    | '/sitemap.xml'
    | '/$'
    | '/about'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/profile/edit'
    | '/courses/$slug'
    | '/enrollment/$protocol'
    | '/administrator/'
    | '/portal/'
    | '/profile/'
    | '/enrollment/'
    | '/authentication/'
    | '/administrator/classes/new'
    | '/administrator/courses/new'
    | '/administrator/partners/new'
    | '/administrator/users/new'
    | '/administrator/classes/'
    | '/administrator/courses/'
    | '/administrator/enrollments/'
    | '/administrator/partners/'
    | '/administrator/users/'
    | '/authentication/invite/$token/'
    | '/administrator/classes/$id/edit'
    | '/administrator/courses/$id/edit'
    | '/administrator/partners/$id/edit'
    | '/administrator/users/$id/edit'
    | '/administrator/classes/$id/'
    | '/administrator/courses/$id/'
    | '/administrator/enrollments/$id/'
    | '/administrator/partners/$id/'
    | '/administrator/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$'
    | '/about'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/profile/edit'
    | '/courses/$slug'
    | '/enrollment/$protocol'
    | '/administrator'
    | '/portal'
    | '/profile'
    | '/enrollment'
    | '/authentication'
    | '/administrator/classes/new'
    | '/administrator/courses/new'
    | '/administrator/partners/new'
    | '/administrator/users/new'
    | '/administrator/classes'
    | '/administrator/courses'
    | '/administrator/enrollments'
    | '/administrator/partners'
    | '/administrator/users'
    | '/authentication/invite/$token'
    | '/administrator/classes/$id/edit'
    | '/administrator/courses/$id/edit'
    | '/administrator/partners/$id/edit'
    | '/administrator/users/$id/edit'
    | '/administrator/classes/$id'
    | '/administrator/courses/$id'
    | '/administrator/enrollments/$id'
    | '/administrator/partners/$id'
    | '/administrator/users/$id'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/authentication'
    | '/sitemap.xml'
    | '/_public/$'
    | '/_public/about'
    | '/_public/partners'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/'
    | '/_private/profile/edit'
    | '/_public/courses/$slug'
    | '/_public/enrollment/$protocol'
    | '/_private/administrator/'
    | '/_private/portal/'
    | '/_private/profile/'
    | '/_public/enrollment/'
    | '/authentication/_sign-in/'
    | '/_private/administrator/classes/new'
    | '/_private/administrator/courses/new'
    | '/_private/administrator/partners/new'
    | '/_private/administrator/users/new'
    | '/_private/administrator/classes/'
    | '/_private/administrator/courses/'
    | '/_private/administrator/enrollments/'
    | '/_private/administrator/partners/'
    | '/_private/administrator/users/'
    | '/authentication/invite/$token/'
    | '/_private/administrator/classes/$id/edit'
    | '/_private/administrator/courses/$id/edit'
    | '/_private/administrator/partners/$id/edit'
    | '/_private/administrator/users/$id/edit'
    | '/_private/administrator/classes/$id/'
    | '/_private/administrator/courses/$id/'
    | '/_private/administrator/enrollments/$id/'
    | '/_private/administrator/partners/$id/'
    | '/_private/administrator/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthenticationLayoutRoute: typeof AuthenticationLayoutRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/partners': {
      id: '/_public/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PublicPartnersRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/administrator/': {
      id: '/_private/administrator/'
      path: '/administrator'
      fullPath: '/administrator/'
      preLoaderRoute: typeof PrivateAdministratorIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/portal/': {
      id: '/_private/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PrivatePortalIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/profile/edit': {
      id: '/_private/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof PrivateProfileEditRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/courses/$slug': {
      id: '/_public/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof PublicCoursesSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/enrollment/': {
      id: '/_public/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof PublicEnrollmentIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/enrollment/$protocol': {
      id: '/_public/enrollment/$protocol'
      path: '/enrollment/$protocol'
      fullPath: '/enrollment/$protocol'
      preLoaderRoute: typeof PublicEnrollmentProtocolRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/authentication/_sign-in/': {
      id: '/authentication/_sign-in/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationSignInIndexRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/_private/administrator/classes/': {
      id: '/_private/administrator/classes/'
      path: '/administrator/classes'
      fullPath: '/administrator/classes/'
      preLoaderRoute: typeof PrivateAdministratorClassesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/classes/new': {
      id: '/_private/administrator/classes/new'
      path: '/administrator/classes/new'
      fullPath: '/administrator/classes/new'
      preLoaderRoute: typeof PrivateAdministratorClassesNewRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/courses/': {
      id: '/_private/administrator/courses/'
      path: '/administrator/courses'
      fullPath: '/administrator/courses/'
      preLoaderRoute: typeof PrivateAdministratorCoursesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/courses/new': {
      id: '/_private/administrator/courses/new'
      path: '/administrator/courses/new'
      fullPath: '/administrator/courses/new'
      preLoaderRoute: typeof PrivateAdministratorCoursesNewLazyRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/enrollments/': {
      id: '/_private/administrator/enrollments/'
      path: '/administrator/enrollments'
      fullPath: '/administrator/enrollments/'
      preLoaderRoute: typeof PrivateAdministratorEnrollmentsIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/partners/': {
      id: '/_private/administrator/partners/'
      path: '/administrator/partners'
      fullPath: '/administrator/partners/'
      preLoaderRoute: typeof PrivateAdministratorPartnersIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/partners/new': {
      id: '/_private/administrator/partners/new'
      path: '/administrator/partners/new'
      fullPath: '/administrator/partners/new'
      preLoaderRoute: typeof PrivateAdministratorPartnersNewLazyRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/users/': {
      id: '/_private/administrator/users/'
      path: '/administrator/users'
      fullPath: '/administrator/users/'
      preLoaderRoute: typeof PrivateAdministratorUsersIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/users/new': {
      id: '/_private/administrator/users/new'
      path: '/administrator/users/new'
      fullPath: '/administrator/users/new'
      preLoaderRoute: typeof PrivateAdministratorUsersNewLazyRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/authentication/invite/$token/': {
      id: '/authentication/invite/$token/'
      path: '/invite/$token'
      fullPath: '/authentication/invite/$token/'
      preLoaderRoute: typeof AuthenticationInviteTokenIndexRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/_private/administrator/classes/$id/': {
      id: '/_private/administrator/classes/$id/'
      path: '/administrator/classes/$id'
      fullPath: '/administrator/classes/$id/'
      preLoaderRoute: typeof PrivateAdministratorClassesIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/classes/$id/edit': {
      id: '/_private/administrator/classes/$id/edit'
      path: '/administrator/classes/$id/edit'
      fullPath: '/administrator/classes/$id/edit'
      preLoaderRoute: typeof PrivateAdministratorClassesIdEditRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/courses/$id/': {
      id: '/_private/administrator/courses/$id/'
      path: '/administrator/courses/$id'
      fullPath: '/administrator/courses/$id/'
      preLoaderRoute: typeof PrivateAdministratorCoursesIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/courses/$id/edit': {
      id: '/_private/administrator/courses/$id/edit'
      path: '/administrator/courses/$id/edit'
      fullPath: '/administrator/courses/$id/edit'
      preLoaderRoute: typeof PrivateAdministratorCoursesIdEditRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/enrollments/$id/': {
      id: '/_private/administrator/enrollments/$id/'
      path: '/administrator/enrollments/$id'
      fullPath: '/administrator/enrollments/$id/'
      preLoaderRoute: typeof PrivateAdministratorEnrollmentsIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/partners/$id/': {
      id: '/_private/administrator/partners/$id/'
      path: '/administrator/partners/$id'
      fullPath: '/administrator/partners/$id/'
      preLoaderRoute: typeof PrivateAdministratorPartnersIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/partners/$id/edit': {
      id: '/_private/administrator/partners/$id/edit'
      path: '/administrator/partners/$id/edit'
      fullPath: '/administrator/partners/$id/edit'
      preLoaderRoute: typeof PrivateAdministratorPartnersIdEditRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/users/$id/': {
      id: '/_private/administrator/users/$id/'
      path: '/administrator/users/$id'
      fullPath: '/administrator/users/$id/'
      preLoaderRoute: typeof PrivateAdministratorUsersIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrator/users/$id/edit': {
      id: '/_private/administrator/users/$id/edit'
      path: '/administrator/users/$id/edit'
      fullPath: '/administrator/users/$id/edit'
      preLoaderRoute: typeof PrivateAdministratorUsersIdEditRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateProfileEditRoute: typeof PrivateProfileEditRoute
  PrivateAdministratorIndexRoute: typeof PrivateAdministratorIndexRoute
  PrivatePortalIndexRoute: typeof PrivatePortalIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivateAdministratorClassesNewRoute: typeof PrivateAdministratorClassesNewRoute
  PrivateAdministratorCoursesNewLazyRoute: typeof PrivateAdministratorCoursesNewLazyRoute
  PrivateAdministratorPartnersNewLazyRoute: typeof PrivateAdministratorPartnersNewLazyRoute
  PrivateAdministratorUsersNewLazyRoute: typeof PrivateAdministratorUsersNewLazyRoute
  PrivateAdministratorClassesIndexRoute: typeof PrivateAdministratorClassesIndexRoute
  PrivateAdministratorCoursesIndexRoute: typeof PrivateAdministratorCoursesIndexRoute
  PrivateAdministratorEnrollmentsIndexRoute: typeof PrivateAdministratorEnrollmentsIndexRoute
  PrivateAdministratorPartnersIndexRoute: typeof PrivateAdministratorPartnersIndexRoute
  PrivateAdministratorUsersIndexRoute: typeof PrivateAdministratorUsersIndexRoute
  PrivateAdministratorClassesIdEditRoute: typeof PrivateAdministratorClassesIdEditRoute
  PrivateAdministratorCoursesIdEditRoute: typeof PrivateAdministratorCoursesIdEditRoute
  PrivateAdministratorPartnersIdEditRoute: typeof PrivateAdministratorPartnersIdEditRoute
  PrivateAdministratorUsersIdEditRoute: typeof PrivateAdministratorUsersIdEditRoute
  PrivateAdministratorClassesIdIndexRoute: typeof PrivateAdministratorClassesIdIndexRoute
  PrivateAdministratorCoursesIdIndexRoute: typeof PrivateAdministratorCoursesIdIndexRoute
  PrivateAdministratorEnrollmentsIdIndexRoute: typeof PrivateAdministratorEnrollmentsIdIndexRoute
  PrivateAdministratorPartnersIdIndexRoute: typeof PrivateAdministratorPartnersIdIndexRoute
  PrivateAdministratorUsersIdIndexRoute: typeof PrivateAdministratorUsersIdIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateProfileEditRoute: PrivateProfileEditRoute,
  PrivateAdministratorIndexRoute: PrivateAdministratorIndexRoute,
  PrivatePortalIndexRoute: PrivatePortalIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivateAdministratorClassesNewRoute: PrivateAdministratorClassesNewRoute,
  PrivateAdministratorCoursesNewLazyRoute:
    PrivateAdministratorCoursesNewLazyRoute,
  PrivateAdministratorPartnersNewLazyRoute:
    PrivateAdministratorPartnersNewLazyRoute,
  PrivateAdministratorUsersNewLazyRoute: PrivateAdministratorUsersNewLazyRoute,
  PrivateAdministratorClassesIndexRoute: PrivateAdministratorClassesIndexRoute,
  PrivateAdministratorCoursesIndexRoute: PrivateAdministratorCoursesIndexRoute,
  PrivateAdministratorEnrollmentsIndexRoute:
    PrivateAdministratorEnrollmentsIndexRoute,
  PrivateAdministratorPartnersIndexRoute:
    PrivateAdministratorPartnersIndexRoute,
  PrivateAdministratorUsersIndexRoute: PrivateAdministratorUsersIndexRoute,
  PrivateAdministratorClassesIdEditRoute:
    PrivateAdministratorClassesIdEditRoute,
  PrivateAdministratorCoursesIdEditRoute:
    PrivateAdministratorCoursesIdEditRoute,
  PrivateAdministratorPartnersIdEditRoute:
    PrivateAdministratorPartnersIdEditRoute,
  PrivateAdministratorUsersIdEditRoute: PrivateAdministratorUsersIdEditRoute,
  PrivateAdministratorClassesIdIndexRoute:
    PrivateAdministratorClassesIdIndexRoute,
  PrivateAdministratorCoursesIdIndexRoute:
    PrivateAdministratorCoursesIdIndexRoute,
  PrivateAdministratorEnrollmentsIdIndexRoute:
    PrivateAdministratorEnrollmentsIdIndexRoute,
  PrivateAdministratorPartnersIdIndexRoute:
    PrivateAdministratorPartnersIdIndexRoute,
  PrivateAdministratorUsersIdIndexRoute: PrivateAdministratorUsersIdIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicAboutRoute: typeof PublicAboutRoute
  PublicPartnersRoute: typeof PublicPartnersRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesSlugRoute: typeof PublicCoursesSlugRoute
  PublicEnrollmentProtocolRoute: typeof PublicEnrollmentProtocolRoute
  PublicEnrollmentIndexRoute: typeof PublicEnrollmentIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicAboutRoute: PublicAboutRoute,
  PublicPartnersRoute: PublicPartnersRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesSlugRoute: PublicCoursesSlugRoute,
  PublicEnrollmentProtocolRoute: PublicEnrollmentProtocolRoute,
  PublicEnrollmentIndexRoute: PublicEnrollmentIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AuthenticationLayoutRouteChildren {
  AuthenticationSignInIndexRoute: typeof AuthenticationSignInIndexRoute
  AuthenticationInviteTokenIndexRoute: typeof AuthenticationInviteTokenIndexRoute
}

const AuthenticationLayoutRouteChildren: AuthenticationLayoutRouteChildren = {
  AuthenticationSignInIndexRoute: AuthenticationSignInIndexRoute,
  AuthenticationInviteTokenIndexRoute: AuthenticationInviteTokenIndexRoute,
}

const AuthenticationLayoutRouteWithChildren =
  AuthenticationLayoutRoute._addFileChildren(AuthenticationLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthenticationLayoutRoute: AuthenticationLayoutRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
